name: Dog API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run Tests
        run: |
          if [ -d "./dog-api-tests" ]; then cd ./dog-api-tests; fi
          mvn test
      - name: Generate Allure Report
        run: |
          if [ -d "./dog-api-tests" ]; then cd ./dog-api-tests; fi
          mvn allure:report
      - uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
            dog-api-tests/target/site/allure-maven-plugin
            target/site/allure-maven-plugin
